# Original data
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain

# Original data + adversarial neg
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg

# Original data + adversarial neg * 2
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0

# Original data + adversarial neg * 4
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0

# Original data + adversarial neg, split robustness
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --split_robustness 0.5
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --split_robustness 0.5
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --split_robustness 0.5
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --split_robustness 0.5

# Original data + adversarial neg * 2
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 2.0 --split_robustness 0.5

# Original data + adversarial neg * 4
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/math/train.jsonl --input_file_type original_math --output_file outputs/sft_data/math/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/math/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-1.5B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-1.5B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0 --split_robustness 0.5
python3 generate_sft_data.py --input_file data/gsm8k/train.jsonl --input_file_type original_gsm8k --output_file outputs/sft_data/gsm8k/Qwen2.5-Math-7B-Instruct/sft.jsonl --included_sample_types original_full --reindex --continue_pretrain --extra_input_files outputs/test_adversarial_results/gsm8k/Qwen2.5-Math-7B-Instruct/train_qwen25-math-cot_-1_seed0_t0.0_s0_e-1_test_result_inspection.xlsx --extra_input_sample_types adversarial_neg --resample_neg 4.0 --split_robustness 0.5
